FROM onlyoffice/documentserver

ENV DB_TYPE=mysql
ENV DB_HOST=${MySQL.MYSQLHOST}
ENV DB_NAME=${MySQL.MYSQLDATABASE}
ENV DB_PORT=${MySQL.MYSQLPORT}
ENV DB_PWD=${MySQL.MYSQLPASSWORD}
ENV DB_USER=${MySQL.MYSQLUSER}
