FROM onlyoffice/documentserver

ENV DB_TYPE=mysql
ENV DB_HOST=${mysql.MYSQLHOST}
ENV DB_NAME=${mysql.MYSQLDATABASE}
ENV DB_PORT=${mysql.MYSQLPORT}
ENV DB_PWD=${mysql.MYSQLPASSWORD}
ENV DB_USER=${mysql.MYSQLUSER}
ENV DB_URL=${{mysql.MYSQL_URL}}
